version: '3.8'
services:
  # Django App
  solopython_backend:
   container_name: django
   build: .
   volumes:
    - .:/app
   ports:
    - 8000:8000
   depends_on:
    - db
    - redis
   tty: true  # Add this line to enable pseudo-terminal allocation
    
  # Database (PostgreSQL)
  db:
   image: postgres
   container_name: postgresql
   restart: always
   environment:
      POSTGRES_DB: solopython_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
   ports:
    - 5432:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  # Redis Cache
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379